version = 1

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["backend/Pipfile"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 88

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "black"
enabled = true
